led.setBrightness(3)
basic.showIcon(IconNames.Heart)
basic.pause(1000)
basic.clearScreen()
basic.forever(function () {
    led.plotBrightness(0, 4, 200)
    led.unplot(1, 4)
    pins.setPull(DigitalPin.P0, PinPullMode.PullUp)
    pins.setPull(DigitalPin.P1, PinPullMode.PullDown)
    basic.pause(100)
    pins.setPull(DigitalPin.P0, PinPullMode.PullDown)
    pins.setPull(DigitalPin.P1, PinPullMode.PullUp)
    led.unplot(0, 4)
    led.plotBrightness(1, 4, 200)
})
